logging.config: classpath:log4j2-spring.xml
---
spring:
   profiles: test
logging.config: classpath:log4j2-spring.xml
---
spring:
   profiles: devel
logging.config: classpath:log4j2-spring.xml
---
spring:
   profiles: prod
logging.config: classpath:log4j2-spring-prod.xml